---

- hosts: kube-all
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: kubernetes/common, tags: common }

- hosts: kube-controllers
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/controller, tags: controller }
    - { role: cni, tags: cni }

- hosts: kube-nodes
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

