---

- name: Add Kubernetes APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Install kubernetes packages
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ pkgs }}"

- name: Lock locked packages
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: "{{ locked_pkgs }}"
