---

- name: Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Install HTTPS APT transport
  when: ansible_os_family == "Debian"
  apt:
    name: "apt-transport-https"
    state: present

- name: Add Docker APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: 'docker'

- name: Install docker engine
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: "docker-ce={{ docker_version }}*"
    state: present

- name: Hold docker version
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: docker-ce
    selection: hold
