---
- name: restart etcd
  command: /bin/true
  notify:
    - etcd | reload systemd
    - reload etcd
    - wait for etcd up

- name: etcd | reload systemd
  command: systemctl daemon-reload

- name: reload etcd
  service:
    name: etcd
    state: restarted

- name: wait for etcd up
  uri:
    url: "https://{{ ip }}:2379/health"
    validate_certs: no
    client_cert: "/etc/etcd/pki/client.pem"
    client_key: "/etc/etcd/pki/client-key.pem"
  register: result
  until: result.status is defined and result.status == 200
  retries: 10
  delay: 5
